---
title: "Data Cleaning"
output: html_document
---

```{r init}
library(dplyr)
```

```{r cleaning}

df <- read.csv("transit-1-16-2026.csv")

df <- df %>%
  mutate(
    City = as.factor(City),
    Country = as.factor(Country)
  )

df$Length <- as.numeric(df$Length)
df$Stations <- as.numeric(df$Stations)
df$TunnelPer <- gsub("%", "", df$TunnelPer)
df$TunnelPer <- as.numeric(df$Stations)
df$Cost.km..2023.dollars. <- as.numeric(df$Cost.km..2023.dollars.)

# Convert to numeric
df$TunnelPer <- as.numeric(df$TunnelPer)

##duration
df$Start.year <- as.numeric(df$Start.year)
df$End.year   <- as.numeric(df$End.year)
df$Duration_years <- df$End.year - df$Start.year

##continent
df <- df %>%
  mutate(
    Continent = case_when(
      Country %in% c("US", "CA", "MX", "PA") ~ "North America",
      Country %in% c("BR", "AR", "CL", "CO", "PE", "EC") ~ "South America",
      Country %in% c("GB", "FR", "DE", "ES", "IT", "NL", "NO",
                     "SE", "DK", "FI", "AT", "BE", "BG",
                     "CZ", "GR", "HU", "CH") ~ "Europe",
      Country %in% c("CN", "JP", "KR", "IN", "HK", "ID",
                     "IL", "IR", "MY", "BD", "TH", "AE",
                     "BH", "KW") ~ "Asia",
      Country %in% c("AU", "NZ") ~ "Oceania",
      Country %in% c("EG", "ZA") ~ "Africa",
      TRUE ~ NA_character_
    ),
    Continent = as.factor(Continent)
  )

print(colnames(df))
```

```{r stats of variables}
par(mfrow = c(3, 1))
## cost per km (inflation adjusted)
plot(density(df$Cost.km..2023.dollars., na.rm = TRUE),
     main = "Cost/km (inflation adjusted) Density",
     xlab = "Cost/km")

missing_cost_km_inf <- is.na(df$Cost.km..2023.dollars.)

barplot(table(missing_cost_km_inf),
        main = "Cost/km (inflation adjusted) Missing",
        names.arg = c("Observed", "Missing"))

barplot(prop.table(table(df$Continent,
                         is.na(df$Cost.km..2023.dollars.)), 1)[,2],
        main = "Cost/km (inflation adjusted) Missing by Continent",
        ylab = "Proportion Missing")


##start year
plot(density(df$Start.year, na.rm = TRUE),
     main = "Start Year Density",
     xlab = "Start Year")

missing_startyear <- is.na(df$Start.year)

barplot(table(missing_startyear),
        main = "Start Year Missing",
        names.arg = c("Observed", "Missing"))

barplot(prop.table(table(df$Continent,
                         is.na(df$Start.year)), 1)[,2],
        main = "Start Year Missing by Continent",
        ylab = "Proportion Missing")

## duration
plot(density(df$Duration_years, na.rm = TRUE),
     main = "Density of Project Duration",
     xlab = "Duration (Years)")

missing_duration <- is.na(df$Duration_years)

barplot(table(missing_duration),
        main = "Missing vs Observed Duration",
        names.arg = c("Observed", "Missing"))

barplot(prop.table(table(df$Continent, is.na(df$Duration_years)), 1)[,2],
        main = "Proportion Missing Duration by Continent")

##length
plot(density(df$Length, na.rm = TRUE),
     main = "Length Density",
     xlab = "Length")

missing_length <- is.na(df$Length)

barplot(table(missing_length),
        main = "Length Missing",
        names.arg = c("Observed", "Missing"))

barplot(prop.table(table(df$Continent,
                         is.na(df$Length)), 1)[,2],
        main = "Length Missing by Continent",
        ylab = "Proportion Missing")

##stations
plot(density(df$Stations, na.rm = TRUE),
     main = "Station Density",
     xlab = "Stations")

missing_stations <- is.na(df$Stations)

barplot(table(missing_stations),
        main = "Stations Missing",
        names.arg = c("Observed", "Missing"))

barplot(prop.table(table(df$Continent,
                         is.na(df$Stations)), 1)[,2],
        main = "Stations Missing by Continent",
        ylab = "Proportion Missing")


##tunnel percentage
plot(density(df$TunnelPer, na.rm = TRUE),
     main = "Tunnel Percentage Density",
     xlab = "Tunnel Percentage")

missing_tunnelper <- is.na(df$TunnelPer)

barplot(table(missing_tunnelper),
        main = "Tunnel Percentage Missing",
        names.arg = c("Observed", "Missing"))

barplot(prop.table(table(df$Continent,
                         is.na(df$TunnelPer)), 1)[,2],
        main = "Tunel Percentage Missing by Continent",
        ylab = "Proportion Missing")

```

```{r missing values combined}
response_vars <- c("Start.year",
                   "Duration_years",
                   "Length",
                   "Stations",
                   "TunnelPer")

###by continent

df$missing_count <- rowSums(is.na(df[response_vars]))

missing_by_continent <- aggregate(missing_count ~ Continent,
                                   data = df, mean,
                                   na.rm = TRUE)

barplot(missing_by_continent$missing_count,
        names.arg = missing_by_continent$Continent,
        las = 2,
        main = "Proportion of Missing Response Variables by Continent",
        ylab = "Proportion Missing")


##by start year 

response_vars_2 <- c("Duration_years",
                   "Length",
                   "Stations",
                   "TunnelPer")

df$missing_count_2 <- rowSums(is.na(df[response_vars_2]))

missing_by_year <- aggregate(missing_count ~ Start.year,
                              data = df, mean,
                              na.rm = TRUE)

plot(missing_by_year$Start.year,
     missing_by_year$missing_count,
     type = "h",
     lwd = 2,
     xlab = "Start Year",
     ylab = "Proportion Missing",
     main = "Proportion of Missing Response Variables by Start Year")
```