---
title: "Merging Code"
output: html_document
---

```{r setup, include=FALSE, message=F, warning=F}
knitr::opts_chunk$set(echo = TRUE)
install.packages("tidytuesdayR")
install.packages("tidyverse")
install.packages("naniar")
install.packages("rnaturalearth")
install.packages("rnaturalearthdata")
require(rnaturalearth)
require(sf)
require(naniar)
require(spdep)
require(ggplot2)
require(stringi)
require(tidyr)
require(dplyr)
require(corrplot)
require(car)
require(lmtest)
```

## Getting the data

```{r}
# Getting the Data
transit_cost_2 <- read.csv("transit-1-16-2026.csv")
gdp_data <- read.csv("world-bank-gdp.csv")
country_code <- read.csv("country-code.csv")
urban <- read.csv("urban-pop.csv")
fed <- read.csv("FEDFUNDS.csv")
```

## Cleaning

```{r}
transit2 <- transit_cost_2[1:1007,c("Country", "City", "Start.year", "End.year", "RR.", "Length", "TunnelPer", "Tunnel", "Elevated", "Atgrade", "Stations", "Platform.Length...Meters.", "Year", "PPP.rate", "Cost.km..2023.dollars.")]

cols <- c("Start.year", "End.year", "RR.", "Length", "Tunnel", "Elevated", "Atgrade", "Stations", "Platform.Length...Meters.", "Year",  "Cost.km..2023.dollars.", "PPP.rate")

for(col in cols){
  transit2[,col] <- as.numeric(transit2[,col])
}

transit2$Years <- transit2$End.year - transit2$Start.year
transit2$real_cost <- transit2$Cost.km..2023.dollars. * transit2$Length
transit2$log_cost <- log(transit2$Cost.km..2023.dollars.)
transit2$log_real_cost <- log(transit2$real_cost)
transit2$TunnelPer <- as.numeric(gsub("%", "", transit2$TunnelPer))
transit2$sqrt_real_cost <- sqrt(transit2$real_cost)

transit2
```


## Continent

```{r}
transit2 <- transit2 %>%
  mutate(
    Continent = case_when(
      Country %in% c("US", "CA", "MX", "PA", "DR") ~ "North America",
      Country %in% c("BR", "AR", "CL", "CO", "PE", "EC") ~ "South America",
      Country %in% c("GB", "FR", "DE", "ES", "IT", "NL", "NO",
                     "SE", "DK", "FI", "AT", "BE", "BG",
                     "CZ", "GR", "HU", "CH", "RU", "UK", "PL", "PT", "RS", "RO", "UA") ~ "Europe",
      Country %in% c("CN", "JP", "KR", "IN", "HK", "ID",
                     "IL", "IR", "MY", "BD", "TH", "AE",
                     "BH", "KW", "PH", "PK", "QA", "SA", "SG", "TR", "TW", "VN") ~ "Asia",
      Country %in% c("AU", "NZ") ~ "Oceania",
      Country %in% c("EG", "ZA") ~ "Africa",
      TRUE ~ NA_character_
    ),
    Continent = as.factor(Continent)
  )

transit2
```

## GDP and Urban Pop

```{r}
code_map <- c(
  "AR" = "Argentina",
  "AT" = "Austria",
  "AU" = "Australia",
  "BD" = "Bangladesh",
  "BE" = "Belgium",
  "BG" = "Bulgaria",
  "BH" = "Bahrain",
  "BR" = "Brazil",
  "CA" = "Canada",
  "CH" = "Switzerland",
  "CL" = "Chile",
  "CN" = "China",
  "CO" = "Colombia",
  "CZ" = "Czechia",
  "DE" = "Germany",
  "DK" = "Denmark",
  "DR" = "Dominican Republic",
  "EC" = "Ecuador",
  "EG" = "Egypt, Arab Rep.",
  "ES" = "Spain",
  "FI" = "Finland",
  "FR" = "France",
  "GB" = "United Kingdom",
  "GR" = "Greece",
  "HK" = "Hong Kong SAR, China",
  "HU" = "Hungary",
  "ID" = "Indonesia",
  "IL" = "Israel",
  "IN" = "India",
  "IR" = "Iran, Islamic Rep.",
  "IT" = "Italy",
  "JP" = "Japan",
  "KR" = "Korea, Rep.",
  "KW" = "Kuwait",
  "MX" = "Mexico",
  "MY" = "Malaysia",
  "NL" = "Netherlands",
  "NO" = "Norway",
  "NZ" = "New Zealand",
  "PA" = "Panama",
  "PE" = "Peru",
  "PH" = "Philippines",
  "PK" = "Pakistan",
  "PL" = "Poland",
  "PT" = "Portugal",
  "QA" = "Qatar",
  "RO" = "Romania",
  "RS" = "Serbia",
  "RU" = "Russian Federation",
  "SA" = "Saudi Arabia",
  "SE" = "Sweden",
  "SG" = "Singapore",
  "TH" = "Thailand",
  "TR" = "Turkiye",
  "TW" = "Taiwan, China",
  "UA" = "Ukraine",
  "UK" = "United Kingdom",
  "US" = "United States",
  "UZ" = "Uzbekistan",
  "VN" = "Viet Nam",
  "ZA" = "South Africa"
)

get_wb_value <- function(df, transit_code, year) {
  if (is.na(transit_code) || is.na(year)) return(NA)
  
  year_col <- paste0("X", year)
  if (!(year_col %in% names(df))) return(NA)
  
  wb_name <- code_map[transit_code]
  if (is.na(wb_name)) return(NA)
  
  val <- df[df$Country.Name == wb_name, year_col]
  if (length(val) == 0) return(NA)
  
  as.numeric(val[1])
}

transit2$gdp <- mapply(
  function(ctry, yr) get_wb_value(gdp_data, ctry, yr),
  transit2$Country,
  transit2$Year
)

transit2$urban_pop <- mapply(
  function(ctry, yr) get_wb_value(urban, ctry, yr),
  transit2$Country,
  transit2$Year
)

```

## Histograms and missing values plot

```{r histograms}
par(mfrow = c(1, 2))

hist(transit2$Cost.km..2023.dollars.,
     main = "Cost per km",
     xlab = "Cost per km")

hist(transit2$log_cost,
     main = "Log Cost per km",
     xlab = "log_cost")

par(mfrow = c(1, 3))

hist(transit2$real_cost,
     main = "Real Cost",
     xlab = "real_cost")

hist(transit2$sqrt_real_cost,
     main = "Square Root Real Cost",
     xlab = "sqrt_real_cost")

hist(transit2$log_real_cost,
     main = "Log Real Cost",
     xlab = "log_real_cost")


#missing values 
gg_miss_var(transit2)

# looking at this plot we decided to ignore platform length, atgrade, and elevated 
#needed to examine is Years was missing randomly

years_missing_summary <- transit2 %>%
  group_by(Continent) %>%
  summarise(
    total_projects = n(),
    missing_years = sum(is.na(Years)),
    prop_missing = missing_years / total_projects
  )
ggplot(years_missing_summary,
       aes(x = reorder(Continent, prop_missing),
           y = prop_missing)) +
  geom_col(fill = "steelblue") +
  coord_flip() +
  labs(
    title = "Proportion of Missing Years by Continent",
    x = "Continent",
    y = "Proportion of Projects with Missing Years"
  )
```

## Imputation
```{r imputation}
transit2_imp <- transit2 %>%
  group_by(Country) %>%
  mutate(
    End.year = ifelse(is.na(End.year),
                      ifelse(!is.na(Start.year),
                        round(Start.year + mean(Years, na.rm = TRUE)),
                        round(Year + 0.5 * mean(Years, na.rm = TRUE))
                        ),
                      End.year),
    Start.year = ifelse(is.na(Start.year),
                      ifelse(!is.na(End.year),
                        round(End.year - mean(Years, na.rm = TRUE)),
                        round(Year - 0.5 * mean(Years, na.rm = TRUE))
                        ),
                      Start.year) # 86 NAs after End.year imputation, 45 after Start.year imputation
  ) %>%
  ungroup()

transit2_imp$Years <- transit2_imp$End.year - transit2_imp$Start.year

keep <- c("Country", "Start.year", "End.year", "RR.", "Length", "TunnelPer", "Tunnel", "Stations", "log_cost", "log_real_cost", "Year", "Cost.km..2023.dollars.", "Years", "real_cost", "Continent", "gdp", "urban_pop", "PPP.rate", "sqrt_real_cost")

df_clean <- na.omit(transit2_imp[keep])

## missing values after imputing 
gg_miss_var(transit2_imp)


```
## cost/km with and without continents
```{r cost/km}
##cost/km model
cost_km <- lm(log_cost ~ Years + Start.year + Length + Stations + TunnelPer + PPP.rate + gdp + urban_pop, df_clean)
summary(cost_km)

step_model_costkm <- step(cost_km, direction = "both")
summary(step_model_costkm)
#step selection removes urban pop

##removed length/station because of correlation (removed stations)
##need to keep only one of PPP rate and gdp because they are deeply connected (model performs better with PPP rate)
cost_km_final <- lm(log_cost ~ Years + Start.year + Length + TunnelPer + PPP.rate, df_clean)
summary(cost_km_final)
par(mfrow = c(2, 2))
plot(cost_km_final)

##one we get fine tuned model, add in continent to see the affect of continent of cost/km
##adding in continents made length insignificant so we remove it 
cost_km_fin <- lm(log_cost ~ Years + Start.year + TunnelPer + Continent + PPP.rate, df_clean)
summary(cost_km_fin)
par(mfrow = c(2, 2))
plot(cost_km_fin)



```

##Cost/km testing
```{r cost/km test}
#multicollinearity
vif(cost_km_cont)

# auto correlation
df_clean_ordered <- df_clean[order(df_clean$Start.year), ]

cost_km_cont_ord <- lm(log_cost ~ Years + Start.year + Continent + TunnelPer + PPP.rate,
                       data = df_clean_ordered)

dwtest(cost_km_cont_ord)

#spatial correlation 
world <- ne_countries(scale = "medium", returnclass = "sf")

df_clean$res <- residuals(cost_km_fin)

country_res <- df_clean %>%
  group_by(Country) %>%
  summarize(mean_res = mean(res))

world_res <- world %>%
  filter(iso_a2 %in% country_res$Country) %>%
  left_join(country_res, by = c("iso_a2" = "Country"))

centroids <- st_centroid(world_res)
coords <- st_coordinates(centroids)

knn <- knearneigh(coords, k = 4)
nb <- knn2nb(knn)

listw <- nb2listw(nb, style = "W")

moran.test(world_res$mean_res, listw)

```



##initial cost model without Continent 

```{r cost}
real_cost <- lm(data=df_clean, real_cost ~ Stations + gdp + RR. + TunnelPer)
summary(cost)

real_cost_sq <- lm(data=df_clean, sqrt(real_cost) ~ Stations + gdp + RR. + TunnelPer)
summary(cost_sq)

real_cost_log <- lm(data=df_clean, log(real_cost) ~ Stations + gdp + RR. + TunnelPer)
summary(cost_log)

par(mfrow = c(2, 2))
plot(cost)
par(mfrow = c(2, 2))
plot(cost_sq)
par(mfrow = c(2, 2))
plot(cost_log)

model_table <- data.frame(
  Model = c("real_cost", "real_cost_sq", "real_cost_log"),
  BIC = c(BIC(real_cost), BIC(real_cost_sq), BIC(real_cost_log)),
  AIC = c(AIC(real_cost), AIC(real_cost_sq), AIC(real_cost_log)),
  Adj_R2 = c(
    summary(real_cost)$adj.r.squared,
    summary(real_cost_sq)$adj.r.squared,
    summary(real_cost_log)$adj.r.squared
  )
)

model_table

```
## Overall cost and continents
```{r cost and continents model}
continent_real_init <- lm(data=df_clean, sqrt(real_cost) ~ Stations + RR. + Tunnel + Years + gdp + Length + TunnelPer + PPP.rate + urban_pop)
summary(continent_real_init)


##removes RR
step_model <- step(continent_real_init, direction = "both")
summary(step_model)

## fine tuned model - removed urban pop and tunnel per bc insignificant - high p - value 
## doesn't make sense to have both length and stations (highly correlated) - remove the one resulting in the best performing model (removed stations)
continent_final <- lm(data=df_clean, sqrt(real_cost) ~ Years + Continent + gdp + Length + TunnelPer)
summary(continent_final)
par(mfrow = c(2, 2))
plot(continent_final)


```
## inspecting outliers
```{r outliers}
df_clean[c(8, 510, 741, 755, 756), ]
```

## Testing  cont model (autiocorrelation, homoskedasticity, multicollinearity)
```{r final model testing}
# multicollinearity
vif(continent_final)

# autocorrelation
df_clean_ordered <- df_clean[order(df_clean$Start.year), ]
continent_final_ord <- lm(data=df_clean_ordered, sqrt(real_cost) ~ Years + Continent + gdp + Length + TunnelPer)
dwtest(continent_final_ord)

res <- residuals(continent_final)

plot(df_clean$Start.year, res,
     xlab = "Start Year",
     ylab = "Residuals",
     main = "Residuals vs Start Year")

abline(h = 0, col = "red")


#spatial correlation


world <- ne_countries(scale = "medium", returnclass = "sf")

df_clean$res <- residuals(continent_final)

country_res <- df_clean %>%
  group_by(Country) %>%
  summarize(mean_res = mean(res))

world_res <- world %>%
  filter(iso_a2 %in% country_res$Country) %>%
  left_join(country_res, by = c("iso_a2" = "Country"))

centroids <- st_centroid(world_res)
coords <- st_coordinates(centroids)

knn <- knearneigh(coords, k = 4)
nb <- knn2nb(knn)

listw <- nb2listw(nb, style = "W")

moran.test(world_res$mean_res, listw)

#ks test
res <- residuals(continent_final)

ks.test(res, "pnorm", mean = mean(res), sd = sd(res))


```

# Corr plot
```{r corr}
#log cost/km 
numeric_vars <- transit2 %>%
  select(log_cost, Years, Start.year,
         Length, Stations, TunnelPer, Tunnel, urban_pop, gdp, PPP.rate)
numeric_vars <- numeric_vars %>%
  filter(complete.cases(.))
cor_matrix <- cor(numeric_vars, use = "pairwise.complete.obs")

corrplot(cor_matrix, method = "color", type = "upper",
         tl.col = "black", tl.srt = 45)

#real cost 
numeric_vars <- transit2 %>%
  select(real_cost, Years, Start.year,
         Length, Stations, TunnelPer, Tunnel, urban_pop, gdp, PPP.rate)
numeric_vars <- numeric_vars %>%
  filter(complete.cases(.))
cor_matrix <- cor(numeric_vars, use = "pairwise.complete.obs")

corrplot(cor_matrix, method = "color", type = "upper",
         tl.col = "black", tl.srt = 45)
```